- name: install pip
  apt:
    name: python-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker:
    name: wartest
    registry: registry.gitlab.com
    image: "xavki/presentations-jenkins/wartest:{{ version }}"
    ports: 8081:8080
    state: started
 
